move incubator/osg-hosted-ce to stable (SOFTWARE-4564)
slateci/slate-catalog pull request #478
Opened 2021-04-21 21:40 UTC by edquist

in collaboration with @brianhlin

2021-04-21 21:46 UTC, brianhlin submitted a review, later dismissed
@edquist and I worked on this together so this LGTM

2021-04-21 21:50 UTC, Mansalu commented
Needs another chart version bump. `3.8.1` collides with the version from the last PR.

2021-04-21 21:50 UTC, Mansalu requested changes

2021-04-21 21:50 UTC, Mansalu commented on stable/osg-hosted-ce/osg-hosted-ce/Chart.yaml
> +version: 3.8.1
```suggestion
version: 3.8.2
```

2021-04-21 22:08 UTC, brianhlin commented
But 3.8.1 is associated with the incubator version. Do the stable/incubator versions have to be distinct?

@edquist one other thing I realized that we're missing is a commented out section in the stable values file for the SciTokens mapping. For a commented out default, please add:

```
# some helpful text here
# SciTokenRemoteUserMapping:
#   - "https://scitokens.org/osg-connect": osg01
```

2021-04-21 22:10 UTC, Mansalu commented
This PR appears to touch the incubator version as well as the stable one.

2021-04-21 22:14 UTC, edquist commented
>This PR appears to touch the incubator version as well as the stable one.

2021-04-21 22:16 UTC, Mansalu commented
You'll either need to remove the incubator changes *or* update the chart version within the incubator `Chart.yaml`. Whichever makes the most sense.

2021-04-23 15:38 UTC, brianhlin commented on stable/osg-hosted-ce/osg-hosted-ce/values.yaml
> +#   - "https://scitokens.org/osg-connect": osg01
```suggestion
    # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/OSG.yaml
    # - "https://scitokens.org/osg-connect": osg01
    # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/GLOW.yaml
    # - "https://chtc.cs.wisc.edu": osg02
    # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/CMS.yaml
    # - "https://cms-auth.web.cern.ch/": osg04
    # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/ATLAS.yaml
    # - "https://atlas-auth.web.cern.ch/": osg09
```

Fleshing out the commented issuers

2021-04-23 15:38 UTC, brianhlin commented
> This PR appears to touch the incubator version as well as the stable one.

Ah right. @edquist go ahead and bump the incubator chart version, too

2021-04-23 19:15 UTC, edquist commented
Updated, lmk if anything else is needed

2021-04-23 19:18 UTC, Mansalu approved these changes
LGTM. Thanks for your patience! 😄

2021-04-23 19:18 UTC, merged